services:

  database:
    container_name: database
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecoride
      MYSQL_USER: bhhdev
      MYSQL_PASSWORD: bhhdev
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/bhhdev/ecoride:latest
    user: "www-data"
    ports:
      - "2000:80"
    depends_on:
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8899:8080"

volumes:
  db_data:
