# config/services.yaml
# Entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    # Put parameters here if needed

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers services as commands, event subscribers, etc.

    # Automatically load all classes in src/
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Automatically load all controllers in src/Controller/
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
