doctrine:
    dbal:
        # Utilisez la variable d'environnement DATABASE_URL
        url: '%env(resolve:DATABASE_URL)%'

        # Version correcte de MariaDB pour Doctrine
        server_version: 'mariadb-10.6.10'

        # Options recommand√©es
        use_savepoints: true
        profiling_collect_backtrace: '%kernel.debug%'

    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            App:
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                is_bundle: false
