security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # ================================
        # CLIENT FIREWALL
        # ================================
        clients:
            pattern: ^/clients
            context: app_front
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_clients_security_login
                check_path: app_clients_security_login
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_clients_security_logout
                target: app_clients_home

        # ================================
        # EMPLOYEE FIREWALL
        # ================================
        employee:
            pattern: ^/employee
            context: app_front
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_employee_login
                check_path: app_employee_login
                enable_csrf: true
            logout:
                path: app_clients_security_logout
                target: app_clients_home

        # ================================
        # ADMIN FIREWALL
        # ================================
        admin:
            pattern: ^/admin
            context: app_front
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                enable_csrf: true
            logout:
                path: app_clients_security_logout
                target: app_clients_home

        # ================================
        # MAIN FIREWALL
        # ================================
        main:
            pattern: ^/  # On couvre tout le site
            context: app_front
            lazy: true
            provider: app_user_provider

            logout:
                path: app_clients_security_logout
                target: app_clients_home

    access_control:
        # MAIN
        - { path: ^/, roles: PUBLIC_ACCESS }

        # CLIENT
        - { path: ^/clients/login, roles: PUBLIC_ACCESS }
        - { path: ^/clients, roles: ROLE_USER }

        # EMPLOYEE
        - { path: ^/employee/login, roles: PUBLIC_ACCESS }
        - { path: ^/employee, roles: ROLE_USER }

        # ADMIN
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
