# security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Client firewall
        clients:
            pattern: ^/(personal_space|profile|account)
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_clients_login
                check_path: app_clients_login
                enable_csrf: true
            logout:
                path: app_clients_logout
                target: /home

        # Employee firewall
        employee:
            pattern: ^/employee
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_employee_login
                check_path: app_employee_login
                enable_csrf: true
            logout:
                path: app_employee_logout
                target: /employee/dashboard

        # Admin firewall
        admin:
            pattern: ^/admin
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                enable_csrf: true
            logout:
                path: app_admin_logout
                target: /admin/dashboard

    # DEV MODE : toutes les routes accessibles
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
